---
repository:
  name: ngx-angora-css
  description: Angora CSS is a library that provides a set of CSS classes to help you build modern web applications. It is based on the [Boostrap Expanded Features Library](https://github.com/LynxPardelle/bootstrap-expanded-features) and the [Bootstrap](https://getbootstrap.com/) framework. It is designed to be easy to use and customize. It is also designed to be responsive and mobile-first.
  homepage: github.com/LynxPardelle/ngx-angora-css
  topics: css, bootstrap, ngx-bootstrap-expanded-features, bootstrap-extended-features, angora-css, ngx-angora-css
  has_wiki: false
  private: false
  has_issues: false
  has_projects: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      required_linear_history: true
      restrictions: null
